### PR TITLE
setup size-plugin-bot

### PR DESCRIPTION
**Pull request by kuldeepkeshwar**
Items:
- [x] Add rollup plugin `rollup-plugin-size`
- [x] Add configuration file(`.github/size-plugin.yml`) for [size-plugin 🤖](https://github.com/kuldeepkeshwar/size-plugin-bot)
- [x] Install [Github App](https://github.com/apps/size-plugin)  👈@tannerlinsley

### CODE REVIEW

**Comment by tannerlinsley** [comment]
I don’t think we’re going to use this any more.

**Comment by kuldeepkeshwar** [comment]
@tannerlinsley I would like to take the feedback for this. Please be as verbose/harsh as possible 🙂, this will help me to build a better experience around the bot usage.

**Comment by tannerlinsley** [comment]
For sure. It’s mostly around commit noise and merge conflicts on the size file. I would honestly rather it work more like this GitHub action: https://github.com/preactjs/compressed-size-action and not touch any files.

**Comment by kuldeepkeshwar** [comment]
Thanks 
+1 for commit noise, soon it will be gone once I put my thoughts in code.

Please do check where I shared my thoughts around the github actions 

https://twitter.com/kuldeepkeshwar/status/1230013232909185025?s=21

**Pull request closed without merging**
